### ISSUE TITLE
Fn: error running docker build: exit status 127

### ISSUE THREAD

**Issue by gpitchai** [oracle-quickstart/oci-arch-iot-streaming#8] opened 2021-12-21 15:37 UTC
I tried to run the code and seeing this error in couple of occasions

null_resource.SetupATPFnPush2OCIR (local-exec): Fn: error running docker build: exit status 127

null_resource.Upload2StreamFnPush2OCIR (local-exec): Fn: error running docker build: exit status 127
I see this error as well
null_resource.SetupATPFnPush2OCIR (local-exec): The command '/bin/sh -c apt-get install libaio1' returned a non-zero code: 127

Appreciate your response. Thanks.

**Comment by lfeldman** [comment] 2021-12-22 09:18
@gpitchai let me retry the code on my end and I will let you know.

**Comment by gpitchai** [comment] 2022-01-04 14:52
looks like the issue occurs, when executing apt-get command.

null_resource.SetupATPFnPush2OCIR (local-exec): Step 33/34 : RUN apt-get install libaio1

null_resource.SetupATPFnPush2OCIR (local-exec):  ---> Running in 52fbd6decfd5

null_resource.SetupATPFnPush2OCIR (local-exec): [91m/bin/sh: apt-get: command not found

null_resource.SetupATPFnPush2OCIR (local-exec): [0m

null_resource.SetupATPFnPush2OCIR (local-exec): The command '/bin/sh -c apt-get install libaio1' returned a non-zero code: 127

**Comment by lfeldman** [comment] 2022-01-04 16:46
This apt-get is executed inside docker according to the [DockerFile](https://github.com/oracle-quickstart/oci-arch-iot-streaming/blob/master/functions/SetupATPFn/Dockerfile) (line 65). What is the version of your docker client?

In my testing env it looks like that:
```
[opc@terraform-server oci-arch-iot-streaming]$ docker version
Client: Docker Engine - Community
 Version:           19.03.11-ol
 API version:       1.40
 Go version:        go1.15.5
 Git commit:        748876d
 Built:             Thu Dec  3 19:36:03 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.5
  Git commit:       748876d
  Built:            Thu Dec  3 19:34:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          v1.3.9
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by lfeldman** [comment] 2022-01-10 14:58
@gpitchai could you please comment on the message above. I am about to close the issue if there is no feedback as I am not able to reproduce this issue.

**Comment by gpitchai** [comment] 2022-01-10 16:18
@lfeldman For me the environment is not created when I run the terraform scripts.

**Comment by lfeldman** [comment] 2022-01-10 16:26
@gpitchai ok, I understand, but the Terraform is using the docker client to build function docker images and push it into OCIR. Could you post here `docker version` from your computer? If it is not possible I will close the ticket.

**Comment by gpitchai** [comment] 2022-01-10 17:53
@lfeldman Docker Version is 19.03.11-ol, same one.

**Comment by lfeldman** [comment] 2022-01-10 18:19
@gpitchai it is pretty weird. Could you please send me all logs for local-exec including docker's STEP1-32 (on STEP33 it has failed)?

**Comment by gpitchai** [comment] 2022-01-10 22:25
@lfeldman I have you an email with all logs. Thanks.

**Comment by lfeldman** [comment] 2022-01-12 16:38
@lfeldman recently I have merged [PR](https://github.com/oracle-quickstart/oci-arch-iot-streaming/pull/9) with the master branch. Could you please retest it in Terraform CLI?

**Comment by lfeldman** [comment] 2022-01-13 10:08
@gpitchai I have tested that in Terraform CLI and ORM and [the latest release](https://github.com/oracle-quickstart/oci-arch-iot-streaming/releases/tag/v1.1.1) works fine. Hope you have the same result. Closing the ticket.

**Closed by lfeldman** 2022-01-13 10:08 UTC
Labels: bug
